In [ ]:
# install libraries
!pip install pandas numpy psycopg2-binary sqlalchemy

  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.0 MB 7.5 MB/s eta 0:00:02
   -------- ------------------------------- 2.4/11.0 MB 6.6 MB/s eta 0:00:02
   -------------- ------------------------- 3.9/11.0 MB 6.9 MB/s eta 0:00:02
   -------------------- ------------------- 5.5/11.0 MB 7.2 MB/s eta 0:00:01
   -------------------------- ------------- 7.3/11.0 MB 7.3 MB/s eta 0:00:01
   -------------------------------- ------- 8.9/11.0 MB 7.4 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 7.6 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 7.4 MB/s  0:00:01
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.8 MB 7.7 MB/s eta 0:00:02
   --------- ----------------------

In [23]:
# import Libraries
import pandas as pd
import numpy as np
from pathlib import Path 

In [41]:
#import Raw csv to pandas dataframe
DATA_DIR = Path(r'C:\Users\Admin\OneDrive\Documents\levelz-project\raw_csv')
df = pd.read_csv(DATA_DIR / 'new_retail_data.csv')

In [42]:
print(df.shape)
df.head()

(302010, 30)


Transaction_ID  Customer_ID                 Name                Email  \
0       8691788.0      37249.0  Michelle Harrington    Ebony39@gmail.com   
1       2174773.0      69749.0          Kelsey Hill     Mark36@gmail.com   
2       6679610.0      30192.0         Scott Jensen    Shane85@gmail.com   
3       7232460.0      62101.0        Joseph Miller     Mary34@gmail.com   
4       4983775.0      27901.0        Debra Coleman  Charles30@gmail.com   

          Phone                      Address        City            State  \
0  1.414787e+09            3959 Amanda Burgs    Dortmund           Berlin   
1  6.852900e+09           82072 Dawn Centers  Nottingham          England   
2  8.362160e+09            4133 Young Canyon     Geelong  New South Wales   
3  2.776752e+09  8148 Thomas Creek Suite 100    Edmonton          Ontario   
4  9.098268e+09    5813 Lori Ports Suite 269     Bristol          England   

   Zipcode    Country  ...  Total_Amount Product_Category  Product_Brand  \
0  77985.0    Germany  ...    324.086270         Clothing           Nike   
1  99071.0         UK  ...    806.707815      Electronics        Samsung   
2  75929.0  Australia  ...   1063.432799            Books  Penguin Books   
3  88420.0     Canada  ...   2466.854021       Home Decor     Home Depot   
4  48704.0         UK  ...    248.553049          Grocery         Nestle   

  Product_Type   Feedback  Shipping_Method Payment_Method Order_Status  \
0       Shorts  Excellent         Same-Day     Debit Card      Shipped   
1       Tablet  Excellent         Standard    Credit Card   Processing   
2   Children's    Average         Same-Day    Credit Card   Processing   
3        Tools  Excellent         Standard         PayPal   Processing   
4    Chocolate        Bad         Standard           Cash      Shipped   

   Ratings           products  
0      5.0     Cycling shorts  
1      4.0         Lenovo Tab  
2      2.0   Sports equipment  
3      4.0      Utility knife  
4      1.0  Chocolate cookies  

[5 rows x 30 columns]

In [43]:
# checking for missing vlaues
print(df.isnull().sum())

Transaction_ID      333
Customer_ID         308
Name                382
Email               347
Phone               362
Address             315
City                248
State               281
Zipcode             340
Country             271
Age                 173
Gender              317
Income              290
Customer_Segment    215
Date                359
Year                350
Month               273
Time                350
Total_Purchases     361
Amount              357
Total_Amount        350
Product_Category    283
Product_Brand       281
Product_Type          0
Feedback            184
Shipping_Method     337
Payment_Method      297
Order_Status        235
Ratings             184
products              0
dtype: int64


In [44]:
# Handling missing values
# Drop missing values
df = df.dropna(subset=['Transaction_ID', 'Customer_ID'])
df.shape

(301369, 30)

In [45]:
# fill categorical fields with placeholders (unknown)

categorical_cols = ['Gender','Customer_Segment','Shipping_Method', 'Payment_Method','Order_Status']
for col in categorical_cols:
    df[col] = df[col].fillna('Unknown')

In [46]:
#Checking the DataType
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 301369 entries, 0 to 302009
Data columns (total 30 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Transaction_ID    301369 non-null  float64
 1   Customer_ID       301369 non-null  float64
 2   Name              300989 non-null  object 
 3   Email             301023 non-null  object 
 4   Phone             301008 non-null  float64
 5   Address           301056 non-null  object 
 6   City              301121 non-null  object 
 7   State             301089 non-null  object 
 8   Zipcode           301029 non-null  float64
 9   Country           301099 non-null  object 
 10  Age               301196 non-null  float64
 11  Gender            301369 non-null  object 
 12  Income            301079 non-null  object 
 13  Customer_Segment  301369 non-null  object 
 14  Date              301010 non-null  object 
 15  Year              301021 non-null  float64
 16  Month             301097 

In [47]:
# converting transaction, Age and customer ID  to integer
df['Transaction_ID'] = df['Transaction_ID'].astype('Int64')
df['Customer_ID'] = df['Customer_ID'].astype('Int64')
df['Age'] = df['Age'].astype('Int64')




In [48]:
# converting phone, zipcodes, and year to string
##df['Phone'] = df['Phone'].astype('str').str.replace(r'\.0$', '', regex=True)
df['Phone'] = df['Phone'].astype('str').str.replace('.0', '', regex=False)
df['Zipcode'] = df['Zipcode'].astype('str').str.replace('.0', '', regex=False)
df['Year'] = df['Year'].astype('str').str.replace('.0', '', regex=False)

In [49]:
# converting date value to date type
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

In [50]:
df.head()

Transaction_ID  Customer_ID                 Name                Email  \
0         8691788        37249  Michelle Harrington    Ebony39@gmail.com   
1         2174773        69749          Kelsey Hill     Mark36@gmail.com   
2         6679610        30192         Scott Jensen    Shane85@gmail.com   
3         7232460        62101        Joseph Miller     Mary34@gmail.com   
4         4983775        27901        Debra Coleman  Charles30@gmail.com   

        Phone                      Address        City            State  \
0  1414786801            3959 Amanda Burgs    Dortmund           Berlin   
1  6852899987           82072 Dawn Centers  Nottingham          England   
2  8362160449            4133 Young Canyon     Geelong  New South Wales   
3  2776751724  8148 Thomas Creek Suite 100    Edmonton          Ontario   
4  9098267635    5813 Lori Ports Suite 269     Bristol          England   

  Zipcode    Country  ...  Total_Amount Product_Category  Product_Brand  \
0   77985    Germany  ...    324.086270         Clothing           Nike   
1   99071         UK  ...    806.707815      Electronics        Samsung   
2   75929  Australia  ...   1063.432799            Books  Penguin Books   
3   88420     Canada  ...   2466.854021       Home Decor     Home Depot   
4   48704         UK  ...    248.553049          Grocery         Nestle   

  Product_Type   Feedback Shipping_Method Payment_Method Order_Status  \
0       Shorts  Excellent        Same-Day     Debit Card      Shipped   
1       Tablet  Excellent        Standard    Credit Card   Processing   
2   Children's    Average        Same-Day    Credit Card   Processing   
3        Tools  Excellent        Standard         PayPal   Processing   
4    Chocolate        Bad        Standard           Cash      Shipped   

   Ratings           products  
0      5.0     Cycling shorts  
1      4.0         Lenovo Tab  
2      2.0   Sports equipment  
3      4.0      Utility knife  
4      1.0  Chocolate cookies  

[5 rows x 30 columns]

In [51]:
df.shape

(301369, 30)

In [52]:
# drop exact duplicate
df = df.drop_duplicates()


# Drop rows with dupe transaction id
df = df.drop_duplicates(subset=['Transaction_ID'])

df.shape



(294174, 30)

In [55]:
# create new columns

# Average spend per purchase
df['Avg_Spend'] = df['Total_Amount'] / df['Total_Purchases']

# Customer Age Group
df['Age_Group'] = pd.cut(
    df['Age'],
    bins=[0, 18, 35, 45, 60, 100],
    labels=['Teen', 'Young Adults', 'Adult', 'Middle Aged', 'Senior']
)

# extract weekday from date
df['Weekday'] = df['Date'].dt.day_name()

In [58]:
# a little bit numpy
# high value customer flag(1 if above median total amount. else 0)
df['High_Value'] = np.where(df['Total_Amount'] > df['Total_Amount'].median(), 1, 0)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 294174 entries, 0 to 299656
Data columns (total 34 columns):
 #   Column            Non-Null Count   Dtype         
---  ------            --------------   -----         
 0   Transaction_ID    294174 non-null  Int64         
 1   Customer_ID       294174 non-null  Int64         
 2   Name              293803 non-null  object        
 3   Email             293838 non-null  object        
 4   Phone             294174 non-null  object        
 5   Address           293866 non-null  object        
 6   City              293930 non-null  object        
 7   State             293903 non-null  object        
 8   Zipcode           294174 non-null  object        
 9   Country           293909 non-null  object        
 10  Age               294005 non-null  Int64         
 11  Gender            294174 non-null  object        
 12  Income            293892 non-null  object        
 13  Customer_Segment  294174 non-null  object        
 14  Date     

In [60]:
# customer rating metric

rating_matrix = df.pivot_table(index='Customer_ID',
                               columns= 'Product_Type',
                               values= 'Ratings',
                               aggfunc='mean').fillna(0)

rating_matrix
                               

Product_Type  Bathroom  Bedding  BlueStar AC  Children's  Chocolate  Coffee  \
Customer_ID                                                                   
10000              0.0      4.0          0.0         0.0        0.0     0.0   
10001              0.0      0.0          0.0         0.0        0.0     0.0   
10002              1.0      0.0          0.0         0.0        0.0     0.0   
10003              0.0      0.0          0.0         0.0        0.0     0.0   
10004              0.0      0.0          0.0         0.0        5.0     0.0   
...                ...      ...          ...         ...        ...     ...   
99995              0.0      2.0          0.0         0.0        0.0     0.0   
99996              0.0      0.0          0.0         0.0        0.0     0.0   
99997              4.0      0.0          0.0         0.0        0.0     0.0   
99998              0.0      0.0          0.0         0.0        0.0     0.0   
99999              0.0      0.0          0.0         0.0        0.0     0.0   

Product_Type  Decorations  Dress  Fiction  Fridge  ...  Shorts  Smartphone  \
Customer_ID                                        ...                       
10000                 0.0    0.0      0.0     0.0  ...     3.0         0.0   
10001                 0.0    0.0      5.0     0.0  ...     0.0         0.0   
10002                 0.0    0.0      0.0     0.0  ...     0.0         0.0   
10003                 0.0    0.0      0.0     3.0  ...     0.0         0.0   
10004                 1.0    0.0      0.0     0.0  ...     0.0         0.0   
...                   ...    ...      ...     ...  ...     ...         ...   
99995                 0.0    0.0      0.0     0.0  ...     2.0         5.0   
99996                 0.0    0.0      0.0     0.0  ...     0.0         0.0   
99997                 0.0    0.0      1.0     4.0  ...     0.0         0.0   
99998                 0.0    0.0      0.0     0.0  ...     0.0         0.0   
99999                 0.0    0.0      0.0     0.0  ...     0.0         0.0   

Product_Type  Snacks  Soft Drink  T-shirt  Tablet  Television  Thriller  \
Customer_ID                                                               
10000            0.0         0.0      0.0     2.0         0.0       0.0   
10001            0.0         1.0      0.0     3.0         0.0       0.0   
10002            0.0         4.0      0.0     0.0         0.0       0.0   
10003            0.0         0.0      0.0     0.0         0.0       0.0   
10004            0.0         0.0      0.0     0.0         0.0       0.0   
...              ...         ...      ...     ...         ...       ...   
99995            0.0         0.0      0.0     0.0         0.0       0.0   
99996            0.0         0.0      4.0     0.0         0.0       0.0   
99997            0.0         5.0      0.0     0.0         0.0       0.0   
99998            0.0         0.0      0.0     5.0         0.0       0.0   
99999            0.0         0.0      0.0     0.0         0.0       0.0   

Product_Type  Tools  Water  
Customer_ID                 
10000           0.0    5.0  
10001           0.0    0.0  
10002           0.0    0.0  
10003           0.0    0.0  
10004           0.0    0.0  
...             ...    ...  
99995           0.0    0.0  
99996           0.0    0.0  
99997           0.0    0.0  
99998           5.0    3.0  
99999           0.0    0.0  

[86545 rows x 33 columns]

In [61]:
ratings_array = rating_matrix.to_numpy()
print(ratings_array)

[[0. 4. 0. ... 0. 0. 5.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [4. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 5. 3.]
 [0. 0. 0. ... 0. 0. 0.]]


In [65]:
# customer table
customers = df[[
    "Customer_ID","Name","Email","Phone","Address","City","State","Zipcode",
    "Country","Age","Gender","Income","Customer_Segment","Age_Group","High_Value"
]].drop_duplicates(subset=["Customer_ID"]).reset_index(drop=True)

customers

Customer_ID                 Name                Email       Phone  \
0            37249  Michelle Harrington    Ebony39@gmail.com  1414786801   
1            69749          Kelsey Hill     Mark36@gmail.com  6852899987   
2            30192         Scott Jensen    Shane85@gmail.com  8362160449   
3            62101        Joseph Miller     Mary34@gmail.com  2776751724   
4            27901        Debra Coleman  Charles30@gmail.com  9098267635   
...            ...                  ...                  ...         ...   
86550        82768       Patricia Burch   Brian100@gmail.com  8274070524   
86551        14485        Beth Mcknight    James17@gmail.com  1433774751   
86552        49840           John Yoder     Anne24@gmail.com  6134998286   
86553        58286         Laura Warren   Alison77@gmail.com  1739609997   
86554        29845     Austin Hernandez     John40@gmail.com  1384901351   

                           Address        City            State Zipcode  \
0                3959 Amanda Burgs    Dortmund           Berlin   77985   
1               82072 Dawn Centers  Nottingham          England   99071   
2                4133 Young Canyon     Geelong  New South Wales   75929   
3      8148 Thomas Creek Suite 100    Edmonton          Ontario   88420   
4        5813 Lori Ports Suite 269     Bristol          England   48704   
...                            ...         ...              ...     ...   
86550           665 Patrick Plains      Denver          Georgia   31819   
86551              409 Harvey Dale     Glasgow          England   33440   
86552           8400 Garrett Forks   Liverpool          England   40670   
86553               443 Luna Wells   Sheffield          England   21523   
86554    9154 Smith Mount Apt. 399      London          Ontario   86762   

         Country  Age  Gender  Income Customer_Segment     Age_Group  \
0        Germany   21    Male     Low          Regular  Young Adults   
1             UK   19  Female     Low          Premium  Young Adults   
2      Australia   48    Male     Low          Regular   Middle Aged   
3         Canada   56    Male    High          Premium   Middle Aged   
4             UK   22    Male     Low          Premium  Young Adults   
...          ...  ...     ...     ...              ...           ...   
86550        USA   59  Female  Medium          Premium   Middle Aged   
86551         UK   49  Female  Medium              New   Middle Aged   
86552         UK   31  Female     Low          Premium  Young Adults   
86553         UK   60  Female     Low          Regular   Middle Aged   
86554     Canada   51  Female     Low              New   Middle Aged   

       High_Value  
0               0  
1               0  
2               1  
3               1  
4               0  
...           ...  
86550           0  
86551           0  
86552           1  
86553           0  
86554           1  

[86555 rows x 15 columns]

In [66]:
# Products table
products = df[
    [
        "Product_Category", "Product_Brand", "Product_Type", "products"
    ]
].drop_duplicates().reset_index(drop=True)
products["Product_ID"] = products.index + 1  # assign unique IDs
products = products[["Product_ID"] + [col for col in products.columns if col != "Product_ID" ]]
products


Product_ID Product_Category  Product_Brand Product_Type  \
0             1         Clothing           Nike       Shorts   
1             2      Electronics        Samsung       Tablet   
2             3            Books  Penguin Books   Children's   
3             4       Home Decor     Home Depot        Tools   
4             5          Grocery         Nestle    Chocolate   
..          ...              ...            ...          ...   
835         836              NaN           Zara        Dress   
836         837            Books            NaN   Children's   
837         838       Home Decor            NaN      Kitchen   
838         839              NaN        Samsung   Television   
839         840              NaN        Samsung       Tablet   

              products  
0       Cycling shorts  
1           Lenovo Tab  
2     Sports equipment  
3        Utility knife  
4    Chocolate cookies  
..                 ...  
835     Cocktail dress  
836    Building blocks  
837          Microwave  
838            QLED TV  
839    Huawei MediaPad  

[840 rows x 5 columns]

In [67]:
orders = df[
    [
        "Transaction_ID", "Customer_ID", "Date", "Year", "Month", "Weekday", "Time",
        "Total_Purchases", "Total_Amount", "Shipping_Method", "products", "Order_Status"
    ]
].drop_duplicates(subset=["Transaction_ID"]).reset_index(drop=True)

orders


Transaction_ID  Customer_ID       Date  Year      Month    Weekday  \
0              8691788        37249 2023-09-18  2023  September     Monday   
1              2174773        69749 2023-12-31  2023   December     Sunday   
2              6679610        30192 2023-04-26  2023      April  Wednesday   
3              7232460        62101 2023-05-08  2023        May     Monday   
4              4983775        27901 2024-01-10  2024    January  Wednesday   
...                ...          ...        ...   ...        ...        ...   
294169         4466731        96551 2023-10-25  2023    October  Wednesday   
294170         1234470        35598 2023-10-15  2023    October     Sunday   
294171         7157113        25148 2023-04-17  2023      April     Monday   
294172         4733214        64906 2023-04-16  2023      April     Sunday   
294173         8201755        48417 2023-10-10  2023    October    Tuesday   

            Time  Total_Purchases  Total_Amount Shipping_Method  \
0       22:03:55              3.0    324.086270        Same-Day   
1        8:42:04              2.0    806.707815        Standard   
2        4:06:29              3.0   1063.432799        Same-Day   
3       14:55:17              7.0   2466.854021        Standard   
4       16:54:07              2.0    248.553049        Standard   
...          ...              ...           ...             ...   
294169   5:01:08              6.0   2676.212987        Standard   
294170  12:53:54              5.0   1563.375261        Standard   
294171  14:54:38              1.0    193.549487        Standard   
294172   9:22:53             10.0   4154.162595         Express   
294173  13:13:48              5.0   2468.016337        Standard   

                 products Order_Status  
0          Cycling shorts      Shipped  
1              Lenovo Tab   Processing  
2        Sports equipment   Processing  
3           Utility knife   Processing  
4       Chocolate cookies      Shipped  
...                   ...          ...  
294169   Grapefruit juice   Processing  
294170              Nokia   Processing  
294171           Thriller    Delivered  
294172          Trail mix   Processing  
294173          Xiaomi Mi      Shipped  

[294174 rows x 12 columns]

In [68]:
payments = df[
    [
        "Transaction_ID", "Amount", "Payment_Method"
    ]
].copy().reset_index(drop=True)
payments["Payment_ID"] = payments.index + 1
payments = payments[["Payment_ID"] + [col for col in payments.columns if col != "Payment_ID"]]

payments


Payment_ID  Transaction_ID      Amount Payment_Method
0                1         8691788  108.028757     Debit Card
1                2         2174773  403.353907    Credit Card
2                3         6679610  354.477600    Credit Card
3                4         7232460  352.407717         PayPal
4                5         4983775  124.276524           Cash
...            ...             ...         ...            ...
294169      294170         4466731  446.035498    Credit Card
294170      294171         1234470  312.675052    Credit Card
294171      294172         7157113  193.549487    Credit Card
294172      294173         4733214  415.416260    Credit Card
294173      294174         8201755  493.603267    Credit Card

[294174 rows x 4 columns]

In [69]:
# Feedback table
feedbacks = df[
    [
        "Transaction_ID", "Product_Type", "Ratings", "Feedback"
    ]
].dropna(subset=["Ratings", "Feedback"], how='all').reset_index(drop=True)  # keep only where at least 1

feedbacks["Feedback_ID"] = feedbacks.index + 1

feedbacks = feedbacks[["Feedback_ID"] + [col for col in feedbacks.columns if col != "Feedback_ID"]]

feedbacks


Feedback_ID  Transaction_ID Product_Type  Ratings   Feedback
0                 1         8691788       Shorts      5.0  Excellent
1                 2         2174773       Tablet      4.0  Excellent
2                 3         6679610   Children's      2.0    Average
3                 4         7232460        Tools      4.0  Excellent
4                 5         4983775    Chocolate      1.0        Bad
...             ...             ...          ...      ...        ...
293989       293990         4466731        Juice      5.0  Excellent
293990       293991         1234470   Smartphone      2.0    Average
293991       293992         7157113      Fiction      1.0        Bad
293992       293993         4733214       Snacks      2.0    Average
293993       293994         8201755   Smartphone      2.0    Average

[293994 rows x 5 columns]

In [70]:

# Export tab
OUT = Path(r'C:\Users\Admin\OneDrive\Documents\levelz-project\processed')
OUT.mkdir(parents=True, exist_ok=True)

customers.to_csv(OUT / 'customers.csv', index=False)
products.to_csv(OUT / 'products.csv', index=False)
orders.to_csv(OUT / 'orders.csv', index=False)
payments.to_csv(OUT / 'payments.csv', index=False)
feedbacks.to_csv(OUT / 'feedbacks.csv', index=False)


In [73]:
import psycopg2

def get_connection():
    connection = psycopg2.connect(
        dbname='Levelz-project',
        host = 'localhost',
        user = 'postgres',
        password = 'London123',
        port='5432'

    )
    return connection

get_connection()




<connection object at 0x0000022434232460; dsn: 'user=postgres password=xxx dbname=Levelz-project host=localhost port=5432', closed: 0>

In [74]:
Cconn = get_connection()

In [75]:
from sqlalchemy import create_engine

db_name ='Levelz-project'
db_host = 'localhost'
db_user = 'postgres'
db_password = 'London123'
db_port='5432'


In [76]:
engine = create_engine(
    f'postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}'
)


In [77]:
# Load DataFrames to PostgreSQL tables
customers.to_sql('customers', engine, index=False, if_exists='replace')
products.to_sql('products', engine, index=False, if_exists='replace')
orders.to_sql('orders', engine, index=False, if_exists='replace')
payments.to_sql('payments', engine, index=False, if_exists='replace')
feedbacks.to_sql('feedbacks', engine, index=False, if_exists='replace')

print("Tables loaded successfully to PostgreSQL.")


Tables loaded successfully to PostgreSQL.
